[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/fragments',
    'runtime',
]

# used locally sometimes...
[patch."https://github.com/fragcolor-xyz/chainblocks"]
chainblocks = { path = "../chainblocks/rust" }
