[workspace]
members = [
    'node',
    'pallets/fragments',
	'pallets/entities',
	'pallets/clamor-tools',
    'runtime',
]

# used locally sometimes...
# [patch."https://github.com/fragcolor-xyz/chainblocks"]
# chainblocks = { path = "../chainblocks/rust" }

[profile.release]
panic = 'unwind'
