version: "3.2"

services:
  dev:
    container_name: fragnova
    image: chainblocks/devenv
    working_dir: /var/www/fragnova
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/home/shards
      - CARGO_TARGET_DIR=/home/shards/target
    volumes:
      - .:/var/www/fragnova
      - cargo-home:/home/shards
    command: bash -c "rustup target add wasm32-unknown-unknown && cargo build --release && ./target/release/fragnova --dev --ws-external"

volumes:
  cargo-home:
