version: "3.2"

services:
  dev:
    container_name: fragnova
    image: chainblocks/devenv
    working_dir: /var/www/fragnova
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/fragnova/.cargo
    volumes:
      - .:/var/www/fragnova
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/fragnova --dev --ws-external"
