[package]
authors = ['Fragcolor <https://github.com/fragcolor-xyz>']
description = 'Protos Asset Store pallet.'
edition = '2021'
license = 'BUSL-1.1'
name = 'pallet-protos-rpc'
readme = 'README.md'
version = '0.0.1'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3" }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
serde = { version = "1", features = ["derive"] }
sp-clamor = { version = '0.1.0', path = '../../../primitives/clamor', default-features = false }
hex = "^0.4.3"

# Substrate Dependencies
[dependencies.sp-api]
git = 'https://github.com/clamor-io/substrate.git'
tag = 'clamor-15-05-2022'
version = '4.0.0-dev'

[dependencies.sp-runtime]
git = 'https://github.com/clamor-io/substrate.git'
tag = 'clamor-15-05-2022'
version = '6.0.0'

[dependencies.sp-rpc]
git = 'https://github.com/clamor-io/substrate.git'
tag = 'clamor-15-05-2022'
version = '6.0.0'

[dependencies.sp-blockchain]
git = 'https://github.com/clamor-io/substrate.git'
tag = 'clamor-15-05-2022'
version = '4.0.0-dev'

[dependencies.pallet-protos-rpc-runtime-api]
path = '../rpc/runtime-api'
version = '0.0.1'

[dev-dependencies]
serde_json = "1"

[dependencies.pallet-protos]
default-features = false
path = '..'
version = '0.0.1'