name: Check Set-Up & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl
          rustup update
          rustup default nightly
          rustup target add wasm32-unknown-unknown

      - uses: chainblocks/setup-ipfs@master
        with:
          run_daemon: true

      - name: Run IPFS Test
        run: |
          cargo build
          RUST_LOG=bitswap=trace cargo run -- --dev --tmp --rpc-external --rpc-port 9933 --rpc-cors all --ws-external --enable-offchain-indexing 1 --rpc-methods=Unsafe --ipfs-server --storage-chain &
          sleep 10
          docker run --rm --user root --network host -v ${{ github.workspace }}:/data chainblocks/cbl cbl /data/chains/fragments-tests.edn
          kill %1

      - name: Check Build
        run: |
          cargo check --release

      - name: Check Build for Benchmarking
        run: >
          pushd node &&
          cargo check --features=runtime-benchmarks --release

      - name: Check Test
        run: |
          cargo test

